artifact_location: file:///c:/Users/sahus/Downloads/dete.v1i.yolov8/runs/mlflow/0
creation_time: 1730474137128
experiment_id: '0'
last_update_time: 1730474137128
lifecycle_stage: active
name: Default
